// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIcMkPK1L2AV8lpqX6u2r4IFQON5Jqueo',
    appId: '1:977915521570:web:86fb9d707757bec623787b',
    messagingSenderId: '977915521570',
    projectId: 'flutterproject-5dd44',
    authDomain: 'flutterproject-5dd44.firebaseapp.com',
    storageBucket: 'flutterproject-5dd44.appspot.com',
    measurementId: 'G-81PVBPK73T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuF3gRnh9oom-r6oiHzF-cq20eSRI5ldc',
    appId: '1:977915521570:android:a000d399ef3360d523787b',
    messagingSenderId: '977915521570',
    projectId: 'flutterproject-5dd44',
    storageBucket: 'flutterproject-5dd44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGGg5roJU9AHQ9MnEAXc6FRjo5KcS01Sk',
    appId: '1:977915521570:ios:12ee6d7ff1b551c623787b',
    messagingSenderId: '977915521570',
    projectId: 'flutterproject-5dd44',
    storageBucket: 'flutterproject-5dd44.appspot.com',
    iosClientId: '977915521570-gnvr3vffd80i37lqq5roulrspm9391fh.apps.googleusercontent.com',
    iosBundleId: 'com.example.scrumBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGGg5roJU9AHQ9MnEAXc6FRjo5KcS01Sk',
    appId: '1:977915521570:ios:12ee6d7ff1b551c623787b',
    messagingSenderId: '977915521570',
    projectId: 'flutterproject-5dd44',
    storageBucket: 'flutterproject-5dd44.appspot.com',
    iosClientId: '977915521570-gnvr3vffd80i37lqq5roulrspm9391fh.apps.googleusercontent.com',
    iosBundleId: 'com.example.scrumBoardApp',
  );
}
